---
- name: Preconfiguration of all nodes
  hosts: all
  become: true
  tags:
    - preconfig
  roles:
    - preconfig

- name: Install container.d and crictl
  hosts: all
  become: true
  tags:
    - containerd
  roles:
    - containerd

- name: Install kubeadm
  hosts: all
  become: true
  tags:
    - kubeadm
  roles:
    - kubeadm

- name: Initialize control plane
  hosts: master-nodes
  become: true
  tags:
    - master_init
  roles:
    - master_init

- name: Join worker nodes to the cluster
  hosts: worker-nodes
  become: true
  tags:
    - worker_join
  roles:
    - worker_join

