- name: Check if Helm binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_bin

- name: Install helm
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-{{ helm_version }}
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: not helm_bin.stat.exists

- name: Run Helm installation script
  ansible.builtin.command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  when: not helm_bin.stat.exists

- name: Check if Cilium is already installed
  kubernetes.core.helm_info:
    name: cilium
    release_namespace: kube-system
  register: cilium_check

- name: Install Cilium with Helm (Kube-proxy replacement mode)
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: "{{ cilium_repository_url }}"
    chart_version: "{{ cilium_chart_version }}"
    release_namespace: kube-system
    wait: true
    values:
      kubeProxyReplacement: true
      k8sServiceHost: "{{  external_api_server }}"
      k8sServicePort: "{{ kube_api_port }}"
      ipam:
        mode: cluster-pool
        operator:
          replicas: 1
          clusterPoolIpv4PodCidrList:
            - "{{ pods_cidr }}"
  when: (cilium_check.releases | default([])) | length == 0
