- name: Pre-configure grub for non-interactive installs
  ansible.builtin.shell: |
    set -o pipefail && echo "grub-pc grub-pc/install_devices_disks_changed multiselect /dev/sda" | debconf-set-selections
    set -o pipefail && echo "grub-pc grub-pc/install_devices multiselect /dev/sda" | debconf-set-selections
  changed_when: false

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    name: '*'
    state: latest
    only_upgrade: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - gpg
      - ca-certificates
      - curl
      - socat
      - conntrack
      - ipset
      - kmod
    state: present
