- name: Check if container.d binary exists
  ansible.builtin.stat:
    path: /usr/bin/containerd
  register: containerd_bin

- name: Upload docker key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: not containerd_bin.stat.exists

- name: Add docker to Apt source
  ansible.builtin.template:
    src: docker.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'
  when: not containerd_bin.stat.exists

- name: Update package manager
  ansible.builtin.apt:
    update_cache: true
  when: not containerd_bin.stat.exists

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
  when: not containerd_bin.stat.exists

- name: Enable containerd
  ansible.builtin.systemd_service:
    enabled: true
    name: containerd.service
    

- name: Create containerd direcotory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create congtainerd configuration file
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd

- name: Prevent containerd from being updated
  ansible.builtin.dpkg_selections:
    name: containerd.io
    selection: hold

- name: Force restart of containerd now
  ansible.builtin.meta: flush_handlers
  